volumes:
  postgres-data:
    driver: local

  redis-data:
    driver: local

services:
  postgres:
    image: postgres:9.6.24
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=harana
      - POSTGRES_USER=harana
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    volumes:
      - redis-data:/var/lib/redis
    command: redis-server --appendonly yes

  sidekiq: &app_base
    build:
      context: .
    image: haranaoss/lio:1
    environment:
      - DATABASE_URL=postgresql://librariesio:not-a-secret@postgres/librariesio
      - REDISCLOUD_URL=redis://redis:6379/1
    volumes:
      - .:/harana.dev
    depends_on:
      - postgres
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml

  web:
    <<: *app_base
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server --port 3000 --binding '0.0.0.0'"
    ports:
      - "3000:3000"
